services:
    Mshavliuk\SignalEventsBundle\Service\SignalHandlerService:
        public: true
        autowire: true
        autoconfigure: true

    signal_events.handle_service: '@Mshavliuk\SignalEventsBundle\Service\SignalHandlerService'