services:
    Mshavliuk\MshavliukSignalEventsBundle\Service\SignalHandlerService:
        public: true
        autowire: true
        autoconfigure: true

    Mshavliuk\MshavliukSignalEventsBundle\Command\SupportedSignalsCommand:
        tags:
            - {name: 'console.command', command: 'signal-events:supported-signals'}

    mshavliuk_signal_events.handle_service: '@Mshavliuk\MshavliukSignalEventsBundle\Service\SignalHandlerService'