parameters:
  signal_events.logging: true
  signal_events.handle_signals: !php/const Mshavliuk\SignalEventsBundle\Service\SignalHandlerService::SUPPORTED_SIGNALS
  signal_events.start_at:
    - !php/const Symfony\Component\Console\ConsoleEvents::COMMAND