<?php

namespace Mshavliuk\SignalEventsBundle;

use Mshavliuk\SignalEventsBundle\DependencyInjection\SignalEventsExtension;
use Mshavliuk\SignalEventsBundle\Service\SignalHandlerService;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class SignalEventsBundle extends Bundle
{
    /**
     * @var SignalHandlerService
     */
    private $signalHandlerService;

    /**
     * {@inheritdoc}
     */
    public function shutdown()
    {
        parent::shutdown(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function boot()
    {
        parent::boot();
    }

    /**
     * {@inheritdoc}
     */
    protected function createContainerExtension()
    {
        return new SignalEventsExtension();
    }
}
